name: continuous-integration
on: push
jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.403'
      - name: Checkout 
        uses: actions/checkout@2.3.3
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --collect "XPlat Code Coverage" --configuration tests.runsettings --results-directory ${{github.workspace}}/codecov
      - name: Upload Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          directory: ${{github.workspace}}/codecov 
