name: continuous-integration
on: push
jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --settings ci.runsettings
      - name: Upload Codecov
        uses: codecov/codecov-action@v1
        with:
          file: "'./FP.UoW-Codecov/**/*.info'"
          fail_ci_if_error: true
          name: FP.UoW-CI
