name: continuous-integration
on: push
jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'
      - name: Checkout 
        uses: actions/checkout@latest
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --collect "XPlat Code Coverage" --settings tests.runsettings --results-directory ./codecov
      - name: Upload Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./codecov/**/*.cobertura.xml
