name: master-continuous-integration
on:
  push:
    branches:
      - 'master'
    paths:
      - '**.cs'
jobs:
  ci:
    runs-on: windows-2019
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Restore FP.UoW solution
        run: dotnet restore
      - name: Build FP.UoW solution
        run: dotnet build
      - name: Test
        run: dotnet test --settings ci.runsettings
      - name: Upload Codecov
        uses: codecov/codecov-action@v1
        with:
          file: "'./FP.UoW-Codecov/**/*.info'"
          fail_ci_if_error: true
          name: FP.UoW-CI
