name: master-continuous-integration
on:
  push:
    branches:
      - 'master'
    paths:
      - '**.cs'
jobs:
  ci:
    runs-on: windows-2019
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.403'
      - name: Checkout source code
        uses: actions/checkout@v2.3.3
      - name: Restore FP.UoW solution
        run: dotnet restore
      - name: Build FP.UoW solution
        run: dotnet build
      - name: Test FP.UoW solution
        run: dotnet test --collect "XPlat Code Coverage" --settings tests.runsettings --results-directory ${{github.workspace}}/codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          files: "'${{github.workspace}}/codecov/**/coverage.info'"
