name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: windows-2019
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Restore FP.UoW solution
        run: dotnet restore
      - name: Build FP.UoW solution
        run: dotnet build
      - name: Test FP.UoW solution
        run: dotnet test --settings ci.runsettings
      - name: Upload Codecov
        uses: codecov/codecov-action@v1
        with:
          file: "'./FP.UoW-Codecov/**/*.info'"
          fail_ci_if_error: true
          name: FP.UoW-CI
      - name: Package FP.UoW solution
        run: dotnet pack --configuration Release --output ${{github.workspace}}/nupkgs
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          release_name: Release ${{github.ref}}
          tag_name: ${{github.ref}}
          draft: false
      # upload-release-asset does not support multiple files at once.
      # To work around that lack of support I have to write a bash script that uses hub to upload assets to a release
      - name: Upload assets with GitHub hub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # See: https://ss64.com/bash/find.html - https://github.com/actions/upload-release-asset/issues/28 - https://unix.stackexchange.com/questions/15308/how-to-use-find-command-to-search-for-multiple-extensions
        # ${GITHUB_REF##*/} is removing a long prefix of */ leaving only the remainder of the tag
        run: hub release edit $(find ${{github.workspace}}/nupkgs -type f \( -name "*.nupkg" -o -name "*.snupkg" \) -printf "-a %p") ${GITHUB_REF##*/}
        shell: bash
      - name: Publish to NuGet
        run: dotnet nuget push ${{github.workspace}}/nupkgs --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
          